#!/usr/bin/env bash
# =============================================================================
#  Install the gateway as a systemd service, so it survives logout and reboot.
#
#      sudo ./install-service.sh
#
#  Paths and user are detected, not hardcoded. Re-running is safe.
#  Override settings by exporting them first, e.g.
#      MAX_CONCURRENCY=3 ALLOWED_MODELS= sudo -E ./install-service.sh
# =============================================================================
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
HERE="$(pwd)"
UNIT=/etc/systemd/system/aicyber-gateway.service

say()  { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
ok()   { printf '\033[32m    ok  %s\033[0m\n' "$*"; }
die()  { printf '\033[31m    !!  %s\033[0m\n' "$*"; exit 1; }

command -v systemctl >/dev/null 2>&1 || die "no systemd here; use ./run.sh under tmux instead"
[ "$(id -u)" -eq 0 ] || die "run with sudo"

# Run as the user who owns the checkout, not as root.
OWNER="$(stat -c '%U' "$HERE" 2>/dev/null || stat -f '%Su' "$HERE")"
[ -n "$OWNER" ] && [ "$OWNER" != "root" ] || OWNER="${SUDO_USER:-root}"

say "Configuration"
echo "    directory      $HERE"
echo "    run as         $OWNER"
echo "    port           ${PORT:-8080}"
echo "    upstream       ${OLLAMA_URL:-http://127.0.0.1:11434}"
echo "    concurrency    ${MAX_CONCURRENCY:-2}"
echo "    models         ${ALLOWED_MODELS-<the five course models>}"

say "Priming the virtualenv as $OWNER"
sudo -u "$OWNER" bash -c "cd '$HERE' && ./run.sh --install-only" \
  || die "could not build the virtualenv as $OWNER -- run ./run.sh --install-only by hand to see why"
ok "virtualenv ready"

say "Writing $UNIT"
{
  echo "# Generated by install-service.sh -- re-run it rather than editing by hand."
  echo "[Unit]"
  echo "Description=AI-Cyber course gateway (fair queue in front of Ollama)"
  echo "After=network-online.target ollama.service"
  echo "Wants=network-online.target"
  # StartLimit* are [Unit] options in current systemd; in [Service] they are
  # ignored with an "Unknown lvalue" warning, so the rate limit would silently
  # not apply and a persistent failure would restart forever.
  echo "StartLimitIntervalSec=60"
  echo "StartLimitBurst=5"
  echo
  echo "[Service]"
  echo "Type=simple"
  echo "User=$OWNER"
  echo "WorkingDirectory=$HERE"
  echo "Environment=\"OLLAMA_URL=${OLLAMA_URL:-http://127.0.0.1:11434}\""
  echo "Environment=\"MAX_CONCURRENCY=${MAX_CONCURRENCY:-2}\""
  echo "Environment=\"PORT=${PORT:-8080}\""
  [ -n "${ALLOWED_MODELS+x}" ] && echo "Environment=\"ALLOWED_MODELS=${ALLOWED_MODELS}\""
  [ -n "${MAX_TOKENS_CAP:-}" ] && echo "Environment=\"MAX_TOKENS_CAP=${MAX_TOKENS_CAP}\""
  echo "ExecStart=$HERE/run.sh"
  echo "Restart=always"
  echo "RestartSec=3"
  echo
  echo "[Install]"
  echo "WantedBy=multi-user.target"
} > "$UNIT"
ok "written"

say "Starting"
systemctl daemon-reload
systemctl enable aicyber-gateway >/dev/null
systemctl restart aicyber-gateway
sleep 4

if systemctl is-active --quiet aicyber-gateway; then
  ok "service active, and enabled at boot"
else
  printf '\033[31m    !!  service is not running. Recent log:\033[0m\n'
  journalctl -u aicyber-gateway -n 25 --no-pager | sed 's/^/        /'
  exit 1
fi

say "Health"
if curl -fsS --max-time 10 "http://127.0.0.1:${PORT:-8080}/healthz" >/tmp/_gwhealth 2>/dev/null; then
  sed 's/^/    /' /tmp/_gwhealth; echo
  ok "gateway answering"
else
  printf '\033[33m    !!  /healthz did not return 200. Usually Ollama is not up yet.\033[0m\n'
  printf '\033[33m        Check:  systemctl status ollama  and  ollama list\033[0m\n'
fi
rm -f /tmp/_gwhealth

cat <<ENDDONE

================================================================================
 Installed. It now starts at boot and restarts on crash.

   systemctl status aicyber-gateway
   journalctl -u aicyber-gateway -f          # live log
   curl -s localhost:${PORT:-8080}/stats | python3 -m json.tool

 To change a setting, re-run this script with it exported:
   MAX_CONCURRENCY=3 sudo -E ./install-service.sh
================================================================================
ENDDONE
